### ISSUE TITLE
Give proper credit

### ISSUE THREAD

**Issue by Proximyst** [MrIvanPlays/Origami#4]
All the patches you've already "given credit" to people in are done incorrectly: set the authors of the patches to the correct people.

These patches are also not credited:

- https://github.com/MrIvanPlays/Origami/blob/master/patches/server/0014-Optimize-Pathfinder.patch - Aikar
- https://github.com/MrIvanPlays/Origami/blob/master/patches/server/0015-Optimize-BehaviorController.patch - Callahan <mr.callahhh@gmail.com>
- https://github.com/MrIvanPlays/Origami/blob/master/patches/server/0016-Revert-Paper-s-chunk-holding-shit.patch - Spottedleaf

Stop being a douche, just credit stuff, it's really not that hard.

**Comment by MrIvanPlays** [comment]
As I mentioned in the commit, I don't know how to change authors.
The BehaviorController changes I didn't know someone had already made them before me, this patch is actually my own and not got from somewhere else.
The Pathfinder changes don't exactly match aikar's changes in the previous patch.

**Comment by Proximyst** [comment]
If it was based on someone else's but you didn't write the base, it's still their patch. You'd write you co-authored it in that case.

For these kind of changes, hand-editing patches is fine. You can also rebase with `edit` on each commit you've gotta change the author in and do `git amend --author="Name <email>"` and then continue rebasing till it's done.
